//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.26 at 10:48:51 PM MESZ 
//


package de.earthdawn.data;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ATTRIBUT_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ATTRIBUT_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required" type="{http://earthdawn.de}ATTRIBUT_name_type" />
 *       &lt;attribute name="steig" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="wert" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ATTRIBUT_type")
public class ATTRIBUTType {

    @XmlAttribute(required = true)
    protected ATTRIBUTNameType name;
    @XmlAttribute(required = true)
    protected BigInteger steig;
    @XmlAttribute(required = true)
    protected BigInteger wert;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link ATTRIBUTNameType }
     *     
     */
    public ATTRIBUTNameType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link ATTRIBUTNameType }
     *     
     */
    public void setName(ATTRIBUTNameType value) {
        this.name = value;
    }

    /**
     * Gets the value of the steig property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSteig() {
        return steig;
    }

    /**
     * Sets the value of the steig property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSteig(BigInteger value) {
        this.steig = value;
    }

    /**
     * Gets the value of the wert property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWert() {
        return wert;
    }

    /**
     * Sets the value of the wert property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWert(BigInteger value) {
        this.wert = value;
    }

}
