//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: see version control commit date
//


package de.earthdawn.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ATTRIBUTE_name_type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ATTRIBUTE_name_type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CHA"/&gt;
 *     &lt;enumeration value="DEX"/&gt;
 *     &lt;enumeration value="STR"/&gt;
 *     &lt;enumeration value="PER"/&gt;
 *     &lt;enumeration value="WIL"/&gt;
 *     &lt;enumeration value="TOU"/&gt;
 *     &lt;enumeration value="na"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "ATTRIBUTE_name_type")
@XmlEnum
public enum ATTRIBUTENameType {

    CHA("CHA"),
    DEX("DEX"),
    STR("STR"),
    PER("PER"),
    WIL("WIL"),
    TOU("TOU"),
    @XmlEnumValue("na")
    NA("na");
    private final String value;

    ATTRIBUTENameType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ATTRIBUTENameType fromValue(String v) {
        for (ATTRIBUTENameType c: ATTRIBUTENameType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
