//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: see version control commit date
//


package de.earthdawn.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BLOODCHARMITEM_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BLOODCHARMITEM_type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://earthdawn.com/datatypes}MAGICITEM_type">
 *       &lt;attribute name="blooddamage" type="{http://earthdawn.com/datatypes}unsigned_int" default="0" />
 *       &lt;attribute name="depatterningrate" type="{http://earthdawn.com/datatypes}unsigned_int" default="0" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BLOODCHARMITEM_type")
public class BLOODCHARMITEMType
    extends MAGICITEMType
{

    @XmlAttribute
    protected Integer blooddamage;
    @XmlAttribute
    protected Integer depatterningrate;

    /**
     * Gets the value of the blooddamage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getBlooddamage() {
        if (blooddamage == null) {
            return  0;
        } else {
            return blooddamage;
        }
    }

    /**
     * Sets the value of the blooddamage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBlooddamage(Integer value) {
        this.blooddamage = value;
    }

    /**
     * Gets the value of the depatterningrate property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getDepatterningrate() {
        if (depatterningrate == null) {
            return  0;
        } else {
            return depatterningrate;
        }
    }

    /**
     * Sets the value of the depatterningrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDepatterningrate(Integer value) {
        this.depatterningrate = value;
    }

}
