//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: see version control commit date
//


package de.earthdawn.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CALCULATEDLEGENDPOINTADJUSTMENTTYPE_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CALCULATEDLEGENDPOINTADJUSTMENTTYPE_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="attributes"/>
 *     &lt;enumeration value="disciplinetalents"/>
 *     &lt;enumeration value="optionaltalents"/>
 *     &lt;enumeration value="knacks"/>
 *     &lt;enumeration value="spells"/>
 *     &lt;enumeration value="skills"/>
 *     &lt;enumeration value="karma"/>
 *     &lt;enumeration value="magicitems"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CALCULATEDLEGENDPOINTADJUSTMENTTYPE_type", namespace = "http://earthdawn.com/character")
@XmlEnum
public enum CALCULATEDLEGENDPOINTADJUSTMENTTYPEType {

    @XmlEnumValue("attributes")
    ATTRIBUTES("attributes"),
    @XmlEnumValue("disciplinetalents")
    DISCIPLINETALENTS("disciplinetalents"),
    @XmlEnumValue("optionaltalents")
    OPTIONALTALENTS("optionaltalents"),
    @XmlEnumValue("knacks")
    KNACKS("knacks"),
    @XmlEnumValue("spells")
    SPELLS("spells"),
    @XmlEnumValue("skills")
    SKILLS("skills"),
    @XmlEnumValue("karma")
    KARMA("karma"),
    @XmlEnumValue("magicitems")
    MAGICITEMS("magicitems");
    private final String value;

    CALCULATEDLEGENDPOINTADJUSTMENTTYPEType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CALCULATEDLEGENDPOINTADJUSTMENTTYPEType fromValue(String v) {
        for (CALCULATEDLEGENDPOINTADJUSTMENTTYPEType c: CALCULATEDLEGENDPOINTADJUSTMENTTYPEType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
