//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: see version control commit date
//


package de.earthdawn.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CALCULATEDLEGENDPOINTADJUSTMENTTYPE_type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CALCULATEDLEGENDPOINTADJUSTMENTTYPE_type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="attributes"/&gt;
 *     &lt;enumeration value="disciplinetalents"/&gt;
 *     &lt;enumeration value="optionaltalents"/&gt;
 *     &lt;enumeration value="knacks"/&gt;
 *     &lt;enumeration value="spells"/&gt;
 *     &lt;enumeration value="skills"/&gt;
 *     &lt;enumeration value="karma"/&gt;
 *     &lt;enumeration value="magicitems"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "CALCULATEDLEGENDPOINTADJUSTMENTTYPE_type", namespace = "http://earthdawn.com/character")
@XmlEnum
public enum CALCULATEDLEGENDPOINTADJUSTMENTTYPEType {

    @XmlEnumValue("attributes")
    ATTRIBUTES("attributes"),
    @XmlEnumValue("disciplinetalents")
    DISCIPLINETALENTS("disciplinetalents"),
    @XmlEnumValue("optionaltalents")
    OPTIONALTALENTS("optionaltalents"),
    @XmlEnumValue("knacks")
    KNACKS("knacks"),
    @XmlEnumValue("spells")
    SPELLS("spells"),
    @XmlEnumValue("skills")
    SKILLS("skills"),
    @XmlEnumValue("karma")
    KARMA("karma"),
    @XmlEnumValue("magicitems")
    MAGICITEMS("magicitems");
    private final String value;

    CALCULATEDLEGENDPOINTADJUSTMENTTYPEType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CALCULATEDLEGENDPOINTADJUSTMENTTYPEType fromValue(String v) {
        for (CALCULATEDLEGENDPOINTADJUSTMENTTYPEType c: CALCULATEDLEGENDPOINTADJUSTMENTTYPEType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
