//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: see version control commit date
//


package de.earthdawn.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for charsheettemplatespell_type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="charsheettemplatespell_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Circle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Element" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Threads" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Weavingdifficulty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Reattuningdifficulty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Castingdifficulty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Range" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Effect" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Effectrarea" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Bookref" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "charsheettemplatespell_type", namespace = "http://earthdawn.com/charsheettemplate", propOrder = {
    "name",
    "circle",
    "element",
    "threads",
    "weavingdifficulty",
    "reattuningdifficulty",
    "castingdifficulty",
    "range",
    "duration",
    "effect",
    "effectrarea",
    "bookref"
})
public class CharsheettemplatespellType {

    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Circle")
    protected String circle;
    @XmlElement(name = "Element")
    protected String element;
    @XmlElement(name = "Threads")
    protected String threads;
    @XmlElement(name = "Weavingdifficulty")
    protected String weavingdifficulty;
    @XmlElement(name = "Reattuningdifficulty")
    protected String reattuningdifficulty;
    @XmlElement(name = "Castingdifficulty")
    protected String castingdifficulty;
    @XmlElement(name = "Range")
    protected String range;
    @XmlElement(name = "Duration")
    protected String duration;
    @XmlElement(name = "Effect")
    protected String effect;
    @XmlElement(name = "Effectrarea")
    protected String effectrarea;
    @XmlElement(name = "Bookref")
    protected String bookref;

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the circle property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCircle() {
        return circle;
    }

    /**
     * Sets the value of the circle property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCircle(String value) {
        this.circle = value;
    }

    /**
     * Gets the value of the element property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getElement() {
        return element;
    }

    /**
     * Sets the value of the element property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setElement(String value) {
        this.element = value;
    }

    /**
     * Gets the value of the threads property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getThreads() {
        return threads;
    }

    /**
     * Sets the value of the threads property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setThreads(String value) {
        this.threads = value;
    }

    /**
     * Gets the value of the weavingdifficulty property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWeavingdifficulty() {
        return weavingdifficulty;
    }

    /**
     * Sets the value of the weavingdifficulty property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWeavingdifficulty(String value) {
        this.weavingdifficulty = value;
    }

    /**
     * Gets the value of the reattuningdifficulty property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReattuningdifficulty() {
        return reattuningdifficulty;
    }

    /**
     * Sets the value of the reattuningdifficulty property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReattuningdifficulty(String value) {
        this.reattuningdifficulty = value;
    }

    /**
     * Gets the value of the castingdifficulty property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCastingdifficulty() {
        return castingdifficulty;
    }

    /**
     * Sets the value of the castingdifficulty property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCastingdifficulty(String value) {
        this.castingdifficulty = value;
    }

    /**
     * Gets the value of the range property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRange() {
        return range;
    }

    /**
     * Sets the value of the range property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRange(String value) {
        this.range = value;
    }

    /**
     * Gets the value of the duration property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDuration(String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the effect property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEffect() {
        return effect;
    }

    /**
     * Sets the value of the effect property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEffect(String value) {
        this.effect = value;
    }

    /**
     * Gets the value of the effectrarea property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEffectrarea() {
        return effectrarea;
    }

    /**
     * Sets the value of the effectrarea property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEffectrarea(String value) {
        this.effectrarea = value;
    }

    /**
     * Gets the value of the bookref property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBookref() {
        return bookref;
    }

    /**
     * Sets the value of the bookref property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBookref(String value) {
        this.bookref = value;
    }

}
