//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: see version control commit date
//


package de.earthdawn.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CHARACTERISTICS_MYSTICARMOR complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CHARACTERISTICS_MYSTICARMOR">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="attribute" use="required" type="{http://earthdawn.com/datatypes}unsigned_int" />
 *       &lt;attribute name="armor" use="required" type="{http://earthdawn.com/datatypes}unsigned_int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CHARACTERISTICS_MYSTICARMOR", namespace = "http://earthdawn.com/characteristics")
public class CHARACTERISTICSMYSTICARMOR {

    @XmlAttribute(name = "attribute", required = true)
    protected int attribute;
    @XmlAttribute(name = "armor", required = true)
    protected int armor;

    /**
     * Gets the value of the attribute property.
     * 
     */
    public int getAttribute() {
        return attribute;
    }

    /**
     * Sets the value of the attribute property.
     * 
     */
    public void setAttribute(int value) {
        this.attribute = value;
    }

    /**
     * Gets the value of the armor property.
     * 
     */
    public int getArmor() {
        return armor;
    }

    /**
     * Sets the value of the armor property.
     * 
     */
    public void setArmor(int value) {
        this.armor = value;
    }

}
