//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: see version control commit date
//


package de.earthdawn.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DURABILITY" type="{http://earthdawn.com/discipline}DISCIPLINEDURABILITY_type"/&gt;
 *         &lt;element name="EASYSKILL" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="CIRCLE" type="{http://earthdawn.com/discipline}DISCIPLINECIRCLE_type" maxOccurs="15" minOccurs="8"/&gt;
 *         &lt;element name="KARMARITUAL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="HALFMAGIC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="lang" use="required" type="{http://earthdawn.com/datatypes}language_type" /&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="bookref" type="{http://www.w3.org/2001/XMLSchema}string" default="" /&gt;
 *       &lt;attribute name="rulesetversion" type="{http://earthdawn.com/datatypes}rulesetversion_type" default="ED3" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "durability",
    "easyskill",
    "circle",
    "karmaritual",
    "halfmagic"
})
@XmlRootElement(name = "DISCIPLINE", namespace = "http://earthdawn.com/discipline")
public class DISCIPLINE {

    @XmlElement(name = "DURABILITY", namespace = "http://earthdawn.com/discipline", required = true)
    protected DISCIPLINEDURABILITYType durability;
    @XmlElement(name = "EASYSKILL", namespace = "http://earthdawn.com/discipline")
    protected List<String> easyskill;
    @XmlElement(name = "CIRCLE", namespace = "http://earthdawn.com/discipline", required = true)
    protected List<DISCIPLINECIRCLEType> circle;
    @XmlElement(name = "KARMARITUAL", namespace = "http://earthdawn.com/discipline")
    protected String karmaritual;
    @XmlElement(name = "HALFMAGIC", namespace = "http://earthdawn.com/discipline")
    protected String halfmagic;
    @XmlAttribute(name = "lang", required = true)
    protected LanguageType lang;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "bookref")
    protected String bookref;
    @XmlAttribute(name = "rulesetversion")
    protected RulesetversionType rulesetversion;

    /**
     * Gets the value of the durability property.
     *
     * @return
     *     possible object is
     *     {@link DISCIPLINEDURABILITYType }
     *
     */
    public DISCIPLINEDURABILITYType getDURABILITY() {
        return durability;
    }

    /**
     * Sets the value of the durability property.
     *
     * @param value
     *     allowed object is
     *     {@link DISCIPLINEDURABILITYType }
     *
     */
    public void setDURABILITY(DISCIPLINEDURABILITYType value) {
        this.durability = value;
    }

    /**
     * Gets the value of the easyskill property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the easyskill property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEASYSKILL().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getEASYSKILL() {
        if (easyskill == null) {
            easyskill = new ArrayList<String>();
        }
        return this.easyskill;
    }

    /**
     * Gets the value of the circle property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the circle property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCIRCLE().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DISCIPLINECIRCLEType }
     *
     *
     */
    public List<DISCIPLINECIRCLEType> getCIRCLE() {
        if (circle == null) {
            circle = new ArrayList<DISCIPLINECIRCLEType>();
        }
        return this.circle;
    }

    /**
     * Gets the value of the karmaritual property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKARMARITUAL() {
        return karmaritual;
    }

    /**
     * Sets the value of the karmaritual property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKARMARITUAL(String value) {
        this.karmaritual = value;
    }

    /**
     * Gets the value of the halfmagic property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHALFMAGIC() {
        return halfmagic;
    }

    /**
     * Sets the value of the halfmagic property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHALFMAGIC(String value) {
        this.halfmagic = value;
    }

    /**
     * Gets the value of the lang property.
     *
     * @return
     *     possible object is
     *     {@link LanguageType }
     *
     */
    public LanguageType getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     *
     * @param value
     *     allowed object is
     *     {@link LanguageType }
     *
     */
    public void setLang(LanguageType value) {
        this.lang = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the bookref property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBookref() {
        if (bookref == null) {
            return "";
        } else {
            return bookref;
        }
    }

    /**
     * Sets the value of the bookref property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBookref(String value) {
        this.bookref = value;
    }

    /**
     * Gets the value of the rulesetversion property.
     *
     * @return
     *     possible object is
     *     {@link RulesetversionType }
     *
     */
    public RulesetversionType getRulesetversion() {
        if (rulesetversion == null) {
            return RulesetversionType.ED_3;
        } else {
            return rulesetversion;
        }
    }

    /**
     * Sets the value of the rulesetversion property.
     *
     * @param value
     *     allowed object is
     *     {@link RulesetversionType }
     *
     */
    public void setRulesetversion(RulesetversionType value) {
        this.rulesetversion = value;
    }

}
