//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: see version control commit date
//


package de.earthdawn.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for elementkind_type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="elementkind_type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="undefined"/&gt;
 *     &lt;enumeration value="wood"/&gt;
 *     &lt;enumeration value="earth"/&gt;
 *     &lt;enumeration value="water"/&gt;
 *     &lt;enumeration value="air"/&gt;
 *     &lt;enumeration value="fire"/&gt;
 *     &lt;enumeration value="illusion"/&gt;
 *     &lt;enumeration value="fear"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "elementkind_type")
@XmlEnum
public enum ElementkindType {

    @XmlEnumValue("undefined")
    UNDEFINED("undefined"),
    @XmlEnumValue("wood")
    WOOD("wood"),
    @XmlEnumValue("earth")
    EARTH("earth"),
    @XmlEnumValue("water")
    WATER("water"),
    @XmlEnumValue("air")
    AIR("air"),
    @XmlEnumValue("fire")
    FIRE("fire"),
    @XmlEnumValue("illusion")
    ILLUSION("illusion"),
    @XmlEnumValue("fear")
    FEAR("fear");
    private final String value;

    ElementkindType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ElementkindType fromValue(String v) {
        for (ElementkindType c: ElementkindType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
