//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.01 at 11:44:24 AM MEZ 
//


package de.earthdawn.data;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FERTIGKEIT_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FERTIGKEIT_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="aktion" use="required" type="{http://earthdawn.de}janein_type" />
 *       &lt;attribute name="attributstufe" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="bezeichnung" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="rang" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ueberanstrengung" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FERTIGKEIT_type")
@XmlSeeAlso({
    TALENTType.class
})
public class FERTIGKEITType {

    @XmlAttribute(required = true)
    protected JaneinType aktion;
    @XmlAttribute(required = true)
    protected BigInteger attributstufe;
    @XmlAttribute(required = true)
    protected String bezeichnung;
    @XmlAttribute(required = true)
    protected BigInteger rang;
    @XmlAttribute(required = true)
    protected BigInteger ueberanstrengung;

    /**
     * Gets the value of the aktion property.
     * 
     * @return
     *     possible object is
     *     {@link JaneinType }
     *     
     */
    public JaneinType getAktion() {
        return aktion;
    }

    /**
     * Sets the value of the aktion property.
     * 
     * @param value
     *     allowed object is
     *     {@link JaneinType }
     *     
     */
    public void setAktion(JaneinType value) {
        this.aktion = value;
    }

    /**
     * Gets the value of the attributstufe property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAttributstufe() {
        return attributstufe;
    }

    /**
     * Sets the value of the attributstufe property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAttributstufe(BigInteger value) {
        this.attributstufe = value;
    }

    /**
     * Gets the value of the bezeichnung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBezeichnung() {
        return bezeichnung;
    }

    /**
     * Sets the value of the bezeichnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBezeichnung(String value) {
        this.bezeichnung = value;
    }

    /**
     * Gets the value of the rang property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRang() {
        return rang;
    }

    /**
     * Sets the value of the rang property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRang(BigInteger value) {
        this.rang = value;
    }

    /**
     * Gets the value of the ueberanstrengung property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUeberanstrengung() {
        return ueberanstrengung;
    }

    /**
     * Sets the value of the ueberanstrengung property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUeberanstrengung(BigInteger value) {
        this.ueberanstrengung = value;
    }

}
