//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.26 at 10:48:51 PM MESZ 
//


package de.earthdawn.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for geschlecht_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="geschlecht_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="m"/>
 *     &lt;enumeration value="w"/>
 *     &lt;enumeration value="-"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "geschlecht_type")
@XmlEnum
public enum GeschlechtType {

    @XmlEnumValue("m")
    M("m"),
    @XmlEnumValue("w")
    W("w"),
    @XmlEnumValue("-")
    MINUS("-");
    private final String value;

    GeschlechtType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GeschlechtType fromValue(String v) {
        for (GeschlechtType c: GeschlechtType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
