//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: see version control commit date
//


package de.earthdawn.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="VERSION" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="LICENCE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AUTHOR" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ABOUT" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "version",
    "licence",
    "author",
    "about"
})
@XmlRootElement(name = "HELP", namespace = "http://earthdawn.com/help")
public class HELP {

    @XmlElement(name = "VERSION", namespace = "http://earthdawn.com/help", required = true)
    protected String version;
    @XmlElement(name = "LICENCE", namespace = "http://earthdawn.com/help", required = true)
    protected String licence;
    @XmlElement(name = "AUTHOR", namespace = "http://earthdawn.com/help", required = true)
    protected String author;
    @XmlElement(name = "ABOUT", namespace = "http://earthdawn.com/help", required = true)
    protected String about;

    /**
     * Gets the value of the version property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVERSION() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVERSION(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the licence property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLICENCE() {
        return licence;
    }

    /**
     * Sets the value of the licence property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLICENCE(String value) {
        this.licence = value;
    }

    /**
     * Gets the value of the author property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAUTHOR() {
        return author;
    }

    /**
     * Sets the value of the author property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAUTHOR(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the about property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getABOUT() {
        return about;
    }

    /**
     * Sets the value of the about property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setABOUT(String value) {
        this.about = value;
    }

}
