//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: see version control commit date
//


package de.earthdawn.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KNACK_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KNACK_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="strain" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="minrank" type="{http://earthdawn.com/datatypes}unsigned_int" default="0" />
 *       &lt;attribute name="mincircle" type="{http://earthdawn.com/datatypes}unsigned_int" default="0" />
 *       &lt;attribute name="bookref" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KNACK_type")
@XmlSeeAlso({
    KNACKBASEType.class
})
public class KNACKType {

    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute
    protected String strain;
    @XmlAttribute
    protected Integer minrank;
    @XmlAttribute
    protected Integer mincircle;
    @XmlAttribute
    protected String bookref;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the strain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrain() {
        if (strain == null) {
            return "0";
        } else {
            return strain;
        }
    }

    /**
     * Sets the value of the strain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrain(String value) {
        this.strain = value;
    }

    /**
     * Gets the value of the minrank property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMinrank() {
        if (minrank == null) {
            return  0;
        } else {
            return minrank;
        }
    }

    /**
     * Sets the value of the minrank property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinrank(Integer value) {
        this.minrank = value;
    }

    /**
     * Gets the value of the mincircle property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMincircle() {
        if (mincircle == null) {
            return  0;
        } else {
            return mincircle;
        }
    }

    /**
     * Sets the value of the mincircle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMincircle(Integer value) {
        this.mincircle = value;
    }

    /**
     * Gets the value of the bookref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookref() {
        if (bookref == null) {
            return "";
        } else {
            return bookref;
        }
    }

    /**
     * Sets the value of the bookref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookref(String value) {
        this.bookref = value;
    }

}
