//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.01 at 11:44:24 AM MEZ 
//


package de.earthdawn.data;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LP_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LP_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="bemerkung" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="lp" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="typ" use="required" type="{http://earthdawn.de}plusminus_type" />
 *       &lt;attribute name="zeit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LP_type")
public class LPType {

    @XmlAttribute(required = true)
    protected String bemerkung;
    @XmlAttribute(required = true)
    protected BigInteger lp;
    @XmlAttribute(required = true)
    protected PlusminusType typ;
    @XmlAttribute(required = true)
    protected String zeit;

    /**
     * Gets the value of the bemerkung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBemerkung() {
        return bemerkung;
    }

    /**
     * Sets the value of the bemerkung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBemerkung(String value) {
        this.bemerkung = value;
    }

    /**
     * Gets the value of the lp property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLp() {
        return lp;
    }

    /**
     * Sets the value of the lp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLp(BigInteger value) {
        this.lp = value;
    }

    /**
     * Gets the value of the typ property.
     * 
     * @return
     *     possible object is
     *     {@link PlusminusType }
     *     
     */
    public PlusminusType getTyp() {
        return typ;
    }

    /**
     * Sets the value of the typ property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlusminusType }
     *     
     */
    public void setTyp(PlusminusType value) {
        this.typ = value;
    }

    /**
     * Gets the value of the zeit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZeit() {
        return zeit;
    }

    /**
     * Sets the value of the zeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZeit(String value) {
        this.zeit = value;
    }

}
