//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: see version control commit date
//


package de.earthdawn.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MOVEMENT_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MOVEMENT_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="flight" type="{http://earthdawn.com/datatypes}unsigned_int" />
 *       &lt;attribute name="flight_string" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="ground" use="required" type="{http://earthdawn.com/datatypes}unsigned_int" />
 *       &lt;attribute name="ground_string" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MOVEMENT_type")
public class MOVEMENTType {

    @XmlAttribute(name = "flight")
    protected Integer flight;
    @XmlAttribute(name = "flight_string")
    protected String flightString;
    @XmlAttribute(name = "ground", required = true)
    protected int ground;
    @XmlAttribute(name = "ground_string")
    protected String groundString;

    /**
     * Gets the value of the flight property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFlight() {
        return flight;
    }

    /**
     * Sets the value of the flight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFlight(Integer value) {
        this.flight = value;
    }

    /**
     * Gets the value of the flightString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightString() {
        if (flightString == null) {
            return "";
        } else {
            return flightString;
        }
    }

    /**
     * Sets the value of the flightString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightString(String value) {
        this.flightString = value;
    }

    /**
     * Gets the value of the ground property.
     * 
     */
    public int getGround() {
        return ground;
    }

    /**
     * Sets the value of the ground property.
     * 
     */
    public void setGround(int value) {
        this.ground = value;
    }

    /**
     * Gets the value of the groundString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroundString() {
        if (groundString == null) {
            return "";
        } else {
            return groundString;
        }
    }

    /**
     * Sets the value of the groundString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroundString(String value) {
        this.groundString = value;
    }

}
