//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: see version control commit date
//


package de.earthdawn.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for namegivermovmenttype_type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="namegivermovmenttype_type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ground"/&gt;
 *     &lt;enumeration value="flight"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "namegivermovmenttype_type", namespace = "http://earthdawn.com/namegiver")
@XmlEnum
public enum NamegivermovmenttypeType {

    @XmlEnumValue("ground")
    GROUND("ground"),
    @XmlEnumValue("flight")
    FLIGHT("flight");
    private final String value;

    NamegivermovmenttypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NamegivermovmenttypeType fromValue(String v) {
        for (NamegivermovmenttypeType c: NamegivermovmenttypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
