//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: see version control commit date
//


package de.earthdawn.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NEWDISCIPLINETALENTADJUSTMENT_type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="NEWDISCIPLINETALENTADJUSTMENT_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="type" use="required" type="{http://earthdawn.com/character}CALCULATEDLEGENDPOINTADJUSTMENTTYPE_type" /&gt;
 *       &lt;attribute name="lowestcircle" use="required" type="{http://earthdawn.com/datatypes}unsigned_int" /&gt;
 *       &lt;attribute name="disciplinenumber" use="required" type="{http://earthdawn.com/datatypes}unsigned_int" /&gt;
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}int" default="0" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NEWDISCIPLINETALENTADJUSTMENT_type", namespace = "http://earthdawn.com/character")
public class NEWDISCIPLINETALENTADJUSTMENTType {

    @XmlAttribute(name = "type", required = true)
    protected CALCULATEDLEGENDPOINTADJUSTMENTTYPEType type;
    @XmlAttribute(name = "lowestcircle", required = true)
    protected int lowestcircle;
    @XmlAttribute(name = "disciplinenumber", required = true)
    protected int disciplinenumber;
    @XmlAttribute(name = "value")
    protected Integer value;

    /**
     * Gets the value of the type property.
     *
     * @return
     *     possible object is
     *     {@link CALCULATEDLEGENDPOINTADJUSTMENTTYPEType }
     *
     */
    public CALCULATEDLEGENDPOINTADJUSTMENTTYPEType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *     allowed object is
     *     {@link CALCULATEDLEGENDPOINTADJUSTMENTTYPEType }
     *
     */
    public void setType(CALCULATEDLEGENDPOINTADJUSTMENTTYPEType value) {
        this.type = value;
    }

    /**
     * Gets the value of the lowestcircle property.
     *
     */
    public int getLowestcircle() {
        return lowestcircle;
    }

    /**
     * Sets the value of the lowestcircle property.
     *
     */
    public void setLowestcircle(int value) {
        this.lowestcircle = value;
    }

    /**
     * Gets the value of the disciplinenumber property.
     *
     */
    public int getDisciplinenumber() {
        return disciplinenumber;
    }

    /**
     * Sets the value of the disciplinenumber property.
     *
     */
    public void setDisciplinenumber(int value) {
        this.disciplinenumber = value;
    }

    /**
     * Gets the value of the value property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public int getValue() {
        if (value == null) {
            return  0;
        } else {
            return value;
        }
    }

    /**
     * Sets the value of the value property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setValue(Integer value) {
        this.value = value;
    }

}
