//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: see version control commit date
//


package de.earthdawn.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.earthdawn.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TRANSLATIONTypeLABEL_QNAME = new QName("http://earthdawn.com/translation", "LABEL");
    private final static QName _TRANSLATIONTypeSHORTCUT_QNAME = new QName("http://earthdawn.com/translation", "SHORTCUT");
    private final static QName _CHARACTERISTICSSTEPDICETABLE_QNAME = new QName("http://earthdawn.com/characteristics", "STEPDICETABLE");
    private final static QName _CHARACTERISTICSDEFENSERAITING_QNAME = new QName("http://earthdawn.com/characteristics", "DEFENSERAITING");
    private final static QName _CHARACTERISTICSENCUMBRANCE_QNAME = new QName("http://earthdawn.com/characteristics", "ENCUMBRANCE");
    private final static QName _CHARACTERISTICSDISCIPLINENR_QNAME = new QName("http://earthdawn.com/characteristics", "DISCIPLINENR");
    private final static QName _CHARACTERISTICSNEWDISCIPLINETALENTCOST_QNAME = new QName("http://earthdawn.com/characteristics", "NEWDISCIPLINETALENTCOST");
    private final static QName _CHARACTERISTICSRESULTLEVEL_QNAME = new QName("http://earthdawn.com/characteristics", "RESULTLEVEL");
    private final static QName _CHARACTERISTICSHEALTHRATING_QNAME = new QName("http://earthdawn.com/characteristics", "HEALTHRATING");
    private final static QName _CHARACTERISTICSLEGENDARYSTATUS_QNAME = new QName("http://earthdawn.com/characteristics", "LEGENDARYSTATUS");
    private final static QName _CHARACTERISTICSATTRIBUTELPCOST_QNAME = new QName("http://earthdawn.com/characteristics", "ATTRIBUTELPCOST");
    private final static QName _CHARACTERISTICSMYSTICARMOR_QNAME = new QName("http://earthdawn.com/characteristics", "MYSTICARMOR");
    private final static QName _CHARACTERISTICSATTRIBUTECOST_QNAME = new QName("http://earthdawn.com/characteristics", "ATTRIBUTECOST");
    private final static QName _CHARACTERISTICSSKILLLPCOST_QNAME = new QName("http://earthdawn.com/characteristics", "SKILLLPCOST");
    private final static QName _CAPABILITIESSKILL_QNAME = new QName("http://earthdawn.com/capability", "SKILL");
    private final static QName _CAPABILITIESTALENT_QNAME = new QName("http://earthdawn.com/capability", "TALENT");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.earthdawn.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ITEMS }
     * 
     */
    public ITEMS createITEMS() {
        return new ITEMS();
    }

    /**
     * Create an instance of {@link ARMORType }
     * 
     */
    public ARMORType createARMORType() {
        return new ARMORType();
    }

    /**
     * Create an instance of {@link SHIELDType }
     * 
     */
    public SHIELDType createSHIELDType() {
        return new SHIELDType();
    }

    /**
     * Create an instance of {@link WEAPONType }
     * 
     */
    public WEAPONType createWEAPONType() {
        return new WEAPONType();
    }

    /**
     * Create an instance of {@link AMMUNITIONType }
     * 
     */
    public AMMUNITIONType createAMMUNITIONType() {
        return new AMMUNITIONType();
    }

    /**
     * Create an instance of {@link MAGICITEMType }
     * 
     */
    public MAGICITEMType createMAGICITEMType() {
        return new MAGICITEMType();
    }

    /**
     * Create an instance of {@link PATTERNITEMType }
     * 
     */
    public PATTERNITEMType createPATTERNITEMType() {
        return new PATTERNITEMType();
    }

    /**
     * Create an instance of {@link THREADITEMType }
     * 
     */
    public THREADITEMType createTHREADITEMType() {
        return new THREADITEMType();
    }

    /**
     * Create an instance of {@link ITEMType }
     * 
     */
    public ITEMType createITEMType() {
        return new ITEMType();
    }

    /**
     * Create an instance of {@link WOUNDType }
     * 
     */
    public WOUNDType createWOUNDType() {
        return new WOUNDType();
    }

    /**
     * Create an instance of {@link SKILLType }
     * 
     */
    public SKILLType createSKILLType() {
        return new SKILLType();
    }

    /**
     * Create an instance of {@link SpelldescriptionType }
     * 
     */
    public SpelldescriptionType createSpelldescriptionType() {
        return new SpelldescriptionType();
    }

    /**
     * Create an instance of {@link DEVOTIONType }
     * 
     */
    public DEVOTIONType createDEVOTIONType() {
        return new DEVOTIONType();
    }

    /**
     * Create an instance of {@link USEDSTARTRANKSType }
     * 
     */
    public USEDSTARTRANKSType createUSEDSTARTRANKSType() {
        return new USEDSTARTRANKSType();
    }

    /**
     * Create an instance of {@link STEPDICEType }
     * 
     */
    public STEPDICEType createSTEPDICEType() {
        return new STEPDICEType();
    }

    /**
     * Create an instance of {@link KARMAABILITYType }
     * 
     */
    public KARMAABILITYType createKARMAABILITYType() {
        return new KARMAABILITYType();
    }

    /**
     * Create an instance of {@link EXPERIENCEType }
     * 
     */
    public EXPERIENCEType createEXPERIENCEType() {
        return new EXPERIENCEType();
    }

    /**
     * Create an instance of {@link MOVEMENTType }
     * 
     */
    public MOVEMENTType createMOVEMENTType() {
        return new MOVEMENTType();
    }

    /**
     * Create an instance of {@link DISCIPLINEBONUSType }
     * 
     */
    public DISCIPLINEBONUSType createDISCIPLINEBONUSType() {
        return new DISCIPLINEBONUSType();
    }

    /**
     * Create an instance of {@link KARMAType }
     * 
     */
    public KARMAType createKARMAType() {
        return new KARMAType();
    }

    /**
     * Create an instance of {@link DEFENSEType }
     * 
     */
    public DEFENSEType createDEFENSEType() {
        return new DEFENSEType();
    }

    /**
     * Create an instance of {@link COINSType }
     * 
     */
    public COINSType createCOINSType() {
        return new COINSType();
    }

    /**
     * Create an instance of {@link SPELLDEFType }
     * 
     */
    public SPELLDEFType createSPELLDEFType() {
        return new SPELLDEFType();
    }

    /**
     * Create an instance of {@link ATTRIBUTEType }
     * 
     */
    public ATTRIBUTEType createATTRIBUTEType() {
        return new ATTRIBUTEType();
    }

    /**
     * Create an instance of {@link APPEARANCEType }
     * 
     */
    public APPEARANCEType createAPPEARANCEType() {
        return new APPEARANCEType();
    }

    /**
     * Create an instance of {@link CAPABILITYType }
     * 
     */
    public CAPABILITYType createCAPABILITYType() {
        return new CAPABILITYType();
    }

    /**
     * Create an instance of {@link INITIATIVEType }
     * 
     */
    public INITIATIVEType createINITIATIVEType() {
        return new INITIATIVEType();
    }

    /**
     * Create an instance of {@link DEFENSEABILITYType }
     * 
     */
    public DEFENSEABILITYType createDEFENSEABILITYType() {
        return new DEFENSEABILITYType();
    }

    /**
     * Create an instance of {@link RECOVERYType }
     * 
     */
    public RECOVERYType createRECOVERYType() {
        return new RECOVERYType();
    }

    /**
     * Create an instance of {@link TALENTABILITYType }
     * 
     */
    public TALENTABILITYType createTALENTABILITYType() {
        return new TALENTABILITYType();
    }

    /**
     * Create an instance of {@link KNACKType }
     * 
     */
    public KNACKType createKNACKType() {
        return new KNACKType();
    }

    /**
     * Create an instance of {@link Base64BinaryType }
     * 
     */
    public Base64BinaryType createBase64BinaryType() {
        return new Base64BinaryType();
    }

    /**
     * Create an instance of {@link SPELLType }
     * 
     */
    public SPELLType createSPELLType() {
        return new SPELLType();
    }

    /**
     * Create an instance of {@link CREATUREType }
     * 
     */
    public CREATUREType createCREATUREType() {
        return new CREATUREType();
    }

    /**
     * Create an instance of {@link DEATHType }
     * 
     */
    public DEATHType createDEATHType() {
        return new DEATHType();
    }

    /**
     * Create an instance of {@link ROLLEDDICEType }
     * 
     */
    public ROLLEDDICEType createROLLEDDICEType() {
        return new ROLLEDDICEType();
    }

    /**
     * Create an instance of {@link RANKHISTORYType }
     * 
     */
    public RANKHISTORYType createRANKHISTORYType() {
        return new RANKHISTORYType();
    }

    /**
     * Create an instance of {@link TALENTTEACHERType }
     * 
     */
    public TALENTTEACHERType createTALENTTEACHERType() {
        return new TALENTTEACHERType();
    }

    /**
     * Create an instance of {@link TALENTType }
     * 
     */
    public TALENTType createTALENTType() {
        return new TALENTType();
    }

    /**
     * Create an instance of {@link PROTECTIONType }
     * 
     */
    public PROTECTIONType createPROTECTIONType() {
        return new PROTECTIONType();
    }

    /**
     * Create an instance of {@link RANKType }
     * 
     */
    public RANKType createRANKType() {
        return new RANKType();
    }

    /**
     * Create an instance of {@link DISCIPLINEType }
     * 
     */
    public DISCIPLINEType createDISCIPLINEType() {
        return new DISCIPLINEType();
    }

    /**
     * Create an instance of {@link THREADRANKType }
     * 
     */
    public THREADRANKType createTHREADRANKType() {
        return new THREADRANKType();
    }

    /**
     * Create an instance of {@link StringlistType }
     * 
     */
    public StringlistType createStringlistType() {
        return new StringlistType();
    }

    /**
     * Create an instance of {@link HEALTHType }
     * 
     */
    public HEALTHType createHEALTHType() {
        return new HEALTHType();
    }

    /**
     * Create an instance of {@link ACCOUNTINGType }
     * 
     */
    public ACCOUNTINGType createACCOUNTINGType() {
        return new ACCOUNTINGType();
    }

    /**
     * Create an instance of {@link CARRYINGType }
     * 
     */
    public CARRYINGType createCARRYINGType() {
        return new CARRYINGType();
    }

    /**
     * Create an instance of {@link DISZIPINABILITYType }
     * 
     */
    public DISZIPINABILITYType createDISZIPINABILITYType() {
        return new DISZIPINABILITYType();
    }

    /**
     * Create an instance of {@link CHARACTERLANGUAGEType }
     * 
     */
    public CHARACTERLANGUAGEType createCHARACTERLANGUAGEType() {
        return new CHARACTERLANGUAGEType();
    }

    /**
     * Create an instance of {@link ECEGUILAYOUT }
     * 
     */
    public ECEGUILAYOUT createECEGUILAYOUT() {
        return new ECEGUILAYOUT();
    }

    /**
     * Create an instance of {@link LAYOUTDIMENSIONType }
     * 
     */
    public LAYOUTDIMENSIONType createLAYOUTDIMENSIONType() {
        return new LAYOUTDIMENSIONType();
    }

    /**
     * Create an instance of {@link LAYOUTTABLEType }
     * 
     */
    public LAYOUTTABLEType createLAYOUTTABLEType() {
        return new LAYOUTTABLEType();
    }

    /**
     * Create an instance of {@link LAYOUTSIZESType }
     * 
     */
    public LAYOUTSIZESType createLAYOUTSIZESType() {
        return new LAYOUTSIZESType();
    }

    /**
     * Create an instance of {@link OPTIONALRULES }
     * 
     */
    public OPTIONALRULES createOPTIONALRULES() {
        return new OPTIONALRULES();
    }

    /**
     * Create an instance of {@link OPTIONALRULESATTRIBUTE }
     * 
     */
    public OPTIONALRULESATTRIBUTE createOPTIONALRULESATTRIBUTE() {
        return new OPTIONALRULESATTRIBUTE();
    }

    /**
     * Create an instance of {@link OPTIONALRULESATTRIBUTEBASEDMOVEMENT }
     * 
     */
    public OPTIONALRULESATTRIBUTEBASEDMOVEMENT createOPTIONALRULESATTRIBUTEBASEDMOVEMENT() {
        return new OPTIONALRULESATTRIBUTEBASEDMOVEMENT();
    }

    /**
     * Create an instance of {@link OPTIONALRULEType }
     * 
     */
    public OPTIONALRULEType createOPTIONALRULEType() {
        return new OPTIONALRULEType();
    }

    /**
     * Create an instance of {@link OPTIONALRULESMULTIUSETALENT }
     * 
     */
    public OPTIONALRULESMULTIUSETALENT createOPTIONALRULESMULTIUSETALENT() {
        return new OPTIONALRULESMULTIUSETALENT();
    }

    /**
     * Create an instance of {@link OPTIONALRULESDEFAULTOPTIONALTALENT }
     * 
     */
    public OPTIONALRULESDEFAULTOPTIONALTALENT createOPTIONALRULESDEFAULTOPTIONALTALENT() {
        return new OPTIONALRULESDEFAULTOPTIONALTALENT();
    }

    /**
     * Create an instance of {@link OPTIONALRULESORIGIN }
     * 
     */
    public OPTIONALRULESORIGIN createOPTIONALRULESORIGIN() {
        return new OPTIONALRULESORIGIN();
    }

    /**
     * Create an instance of {@link NAMESTARTINGWEAPONSType }
     * 
     */
    public NAMESTARTINGWEAPONSType createNAMESTARTINGWEAPONSType() {
        return new NAMESTARTINGWEAPONSType();
    }

    /**
     * Create an instance of {@link NAMESTARTINGITEMSType }
     * 
     */
    public NAMESTARTINGITEMSType createNAMESTARTINGITEMSType() {
        return new NAMESTARTINGITEMSType();
    }

    /**
     * Create an instance of {@link NAMESTARTINGSKILLSType }
     * 
     */
    public NAMESTARTINGSKILLSType createNAMESTARTINGSKILLSType() {
        return new NAMESTARTINGSKILLSType();
    }

    /**
     * Create an instance of {@link OPTIONALRULESDEFAULTLANGUAGE }
     * 
     */
    public OPTIONALRULESDEFAULTLANGUAGE createOPTIONALRULESDEFAULTLANGUAGE() {
        return new OPTIONALRULESDEFAULTLANGUAGE();
    }

    /**
     * Create an instance of {@link SPELLS }
     * 
     */
    public SPELLS createSPELLS() {
        return new SPELLS();
    }

    /**
     * Create an instance of {@link NAMEGIVERS }
     * 
     */
    public NAMEGIVERS createNAMEGIVERS() {
        return new NAMEGIVERS();
    }

    /**
     * Create an instance of {@link NAMEGIVERABILITYType }
     * 
     */
    public NAMEGIVERABILITYType createNAMEGIVERABILITYType() {
        return new NAMEGIVERABILITYType();
    }

    /**
     * Create an instance of {@link NAMEGIVERMOVEMENTType }
     * 
     */
    public NAMEGIVERMOVEMENTType createNAMEGIVERMOVEMENTType() {
        return new NAMEGIVERMOVEMENTType();
    }

    /**
     * Create an instance of {@link NAMEVALUEType }
     * 
     */
    public NAMEVALUEType createNAMEVALUEType() {
        return new NAMEVALUEType();
    }

    /**
     * Create an instance of {@link SPELLDESCRIPTIONS }
     * 
     */
    public SPELLDESCRIPTIONS createSPELLDESCRIPTIONS() {
        return new SPELLDESCRIPTIONS();
    }

    /**
     * Create an instance of {@link HELP }
     * 
     */
    public HELP createHELP() {
        return new HELP();
    }

    /**
     * Create an instance of {@link KNACKS }
     * 
     */
    public KNACKS createKNACKS() {
        return new KNACKS();
    }

    /**
     * Create an instance of {@link KNACKBASEType }
     * 
     */
    public KNACKBASEType createKNACKBASEType() {
        return new KNACKBASEType();
    }

    /**
     * Create an instance of {@link EDRANDOMNAME }
     * 
     */
    public EDRANDOMNAME createEDRANDOMNAME() {
        return new EDRANDOMNAME();
    }

    /**
     * Create an instance of {@link RANDOMNAMERACEType }
     * 
     */
    public RANDOMNAMERACEType createRANDOMNAMERACEType() {
        return new RANDOMNAMERACEType();
    }

    /**
     * Create an instance of {@link RandomnameNamesType }
     * 
     */
    public RandomnameNamesType createRandomnameNamesType() {
        return new RandomnameNamesType();
    }

    /**
     * Create an instance of {@link EDRANDOMCHARACTERTEMPLATE }
     * 
     */
    public EDRANDOMCHARACTERTEMPLATE createEDRANDOMCHARACTERTEMPLATE() {
        return new EDRANDOMCHARACTERTEMPLATE();
    }

    /**
     * Create an instance of {@link WeightedstringlistType }
     * 
     */
    public WeightedstringlistType createWeightedstringlistType() {
        return new WeightedstringlistType();
    }

    /**
     * Create an instance of {@link RANDOMATTRIBUTESType }
     * 
     */
    public RANDOMATTRIBUTESType createRANDOMATTRIBUTESType() {
        return new RANDOMATTRIBUTESType();
    }

    /**
     * Create an instance of {@link RANDOMSPELLCATEGORYType }
     * 
     */
    public RANDOMSPELLCATEGORYType createRANDOMSPELLCATEGORYType() {
        return new RANDOMSPELLCATEGORYType();
    }

    /**
     * Create an instance of {@link RANDOMITEMCATEGORYType }
     * 
     */
    public RANDOMITEMCATEGORYType createRANDOMITEMCATEGORYType() {
        return new RANDOMITEMCATEGORYType();
    }

    /**
     * Create an instance of {@link CHARACTERISTICS }
     * 
     */
    public CHARACTERISTICS createCHARACTERISTICS() {
        return new CHARACTERISTICS();
    }

    /**
     * Create an instance of {@link CHARACTERISTICSENCUMBRANCE }
     * 
     */
    public CHARACTERISTICSENCUMBRANCE createCHARACTERISTICSENCUMBRANCE() {
        return new CHARACTERISTICSENCUMBRANCE();
    }

    /**
     * Create an instance of {@link CHARACTERISTICSDEFENSERAITING }
     * 
     */
    public CHARACTERISTICSDEFENSERAITING createCHARACTERISTICSDEFENSERAITING() {
        return new CHARACTERISTICSDEFENSERAITING();
    }

    /**
     * Create an instance of {@link CHARACTERISTICSMYSTICARMOR }
     * 
     */
    public CHARACTERISTICSMYSTICARMOR createCHARACTERISTICSMYSTICARMOR() {
        return new CHARACTERISTICSMYSTICARMOR();
    }

    /**
     * Create an instance of {@link CHARACTERISTICSATTRIBUTECOST }
     * 
     */
    public CHARACTERISTICSATTRIBUTECOST createCHARACTERISTICSATTRIBUTECOST() {
        return new CHARACTERISTICSATTRIBUTECOST();
    }

    /**
     * Create an instance of {@link CHARACTERISTICSHEALTHRATING }
     * 
     */
    public CHARACTERISTICSHEALTHRATING createCHARACTERISTICSHEALTHRATING() {
        return new CHARACTERISTICSHEALTHRATING();
    }

    /**
     * Create an instance of {@link CHARACTERISTICSSTEPDICETABLE }
     * 
     */
    public CHARACTERISTICSSTEPDICETABLE createCHARACTERISTICSSTEPDICETABLE() {
        return new CHARACTERISTICSSTEPDICETABLE();
    }

    /**
     * Create an instance of {@link CHARACTERISTICSDISCIPLINENR }
     * 
     */
    public CHARACTERISTICSDISCIPLINENR createCHARACTERISTICSDISCIPLINENR() {
        return new CHARACTERISTICSDISCIPLINENR();
    }

    /**
     * Create an instance of {@link CHARACTERISTICSCOST }
     * 
     */
    public CHARACTERISTICSCOST createCHARACTERISTICSCOST() {
        return new CHARACTERISTICSCOST();
    }

    /**
     * Create an instance of {@link CHARACTERISTICSLEGENDARYSTATUS }
     * 
     */
    public CHARACTERISTICSLEGENDARYSTATUS createCHARACTERISTICSLEGENDARYSTATUS() {
        return new CHARACTERISTICSLEGENDARYSTATUS();
    }

    /**
     * Create an instance of {@link CHARACTERISTICSRESULTLEVEL }
     * 
     */
    public CHARACTERISTICSRESULTLEVEL createCHARACTERISTICSRESULTLEVEL() {
        return new CHARACTERISTICSRESULTLEVEL();
    }

    /**
     * Create an instance of {@link CHARACTERISTICSNEWDISCIPLINETALENTCOST }
     * 
     */
    public CHARACTERISTICSNEWDISCIPLINETALENTCOST createCHARACTERISTICSNEWDISCIPLINETALENTCOST() {
        return new CHARACTERISTICSNEWDISCIPLINETALENTCOST();
    }

    /**
     * Create an instance of {@link CHARACTERISTICSCIRCLE }
     * 
     */
    public CHARACTERISTICSCIRCLE createCHARACTERISTICSCIRCLE() {
        return new CHARACTERISTICSCIRCLE();
    }

    /**
     * Create an instance of {@link CHARACTERISTICSNEWDISCIPLINETALENTCOSTDISCIPLINE }
     * 
     */
    public CHARACTERISTICSNEWDISCIPLINETALENTCOSTDISCIPLINE createCHARACTERISTICSNEWDISCIPLINETALENTCOSTDISCIPLINE() {
        return new CHARACTERISTICSNEWDISCIPLINETALENTCOSTDISCIPLINE();
    }

    /**
     * Create an instance of {@link CAPABILITIES }
     * 
     */
    public CAPABILITIES createCAPABILITIES() {
        return new CAPABILITIES();
    }

    /**
     * Create an instance of {@link DISCIPLINE }
     * 
     */
    public DISCIPLINE createDISCIPLINE() {
        return new DISCIPLINE();
    }

    /**
     * Create an instance of {@link DISCIPLINEDURABILITYType }
     * 
     */
    public DISCIPLINEDURABILITYType createDISCIPLINEDURABILITYType() {
        return new DISCIPLINEDURABILITYType();
    }

    /**
     * Create an instance of {@link DISCIPLINECIRCLEType }
     * 
     */
    public DISCIPLINECIRCLEType createDISCIPLINECIRCLEType() {
        return new DISCIPLINECIRCLEType();
    }

    /**
     * Create an instance of {@link DISCIPLINESPELLType }
     * 
     */
    public DISCIPLINESPELLType createDISCIPLINESPELLType() {
        return new DISCIPLINESPELLType();
    }

    /**
     * Create an instance of {@link FOREIGNTALENTSType }
     * 
     */
    public FOREIGNTALENTSType createFOREIGNTALENTSType() {
        return new FOREIGNTALENTSType();
    }

    /**
     * Create an instance of {@link EDCHARACTER }
     * 
     */
    public EDCHARACTER createEDCHARACTER() {
        return new EDCHARACTER();
    }

    /**
     * Create an instance of {@link CALCULATEDLEGENDPOINTSType }
     * 
     */
    public CALCULATEDLEGENDPOINTSType createCALCULATEDLEGENDPOINTSType() {
        return new CALCULATEDLEGENDPOINTSType();
    }

    /**
     * Create an instance of {@link NEWDISCIPLINETALENTADJUSTMENTType }
     * 
     */
    public NEWDISCIPLINETALENTADJUSTMENTType createNEWDISCIPLINETALENTADJUSTMENTType() {
        return new NEWDISCIPLINETALENTADJUSTMENTType();
    }

    /**
     * Create an instance of {@link CALCULATEDLEGENDPOINTADJUSTMENTType }
     * 
     */
    public CALCULATEDLEGENDPOINTADJUSTMENTType createCALCULATEDLEGENDPOINTADJUSTMENTType() {
        return new CALCULATEDLEGENDPOINTADJUSTMENTType();
    }

    /**
     * Create an instance of {@link TRANSLATIONS }
     * 
     */
    public TRANSLATIONS createTRANSLATIONS() {
        return new TRANSLATIONS();
    }

    /**
     * Create an instance of {@link NAMESATTRIBUTESType }
     * 
     */
    public NAMESATTRIBUTESType createNAMESATTRIBUTESType() {
        return new NAMESATTRIBUTESType();
    }

    /**
     * Create an instance of {@link NAMESACTIONSType }
     * 
     */
    public NAMESACTIONSType createNAMESACTIONSType() {
        return new NAMESACTIONSType();
    }

    /**
     * Create an instance of {@link TRANSLATIONType }
     * 
     */
    public TRANSLATIONType createTRANSLATIONType() {
        return new TRANSLATIONType();
    }

    /**
     * Create an instance of {@link NAMESPELLWEAVINGType }
     * 
     */
    public NAMESPELLWEAVINGType createNAMESPELLWEAVINGType() {
        return new NAMESPELLWEAVINGType();
    }

    /**
     * Create an instance of {@link NAMESACTIONType }
     * 
     */
    public NAMESACTIONType createNAMESACTIONType() {
        return new NAMESACTIONType();
    }

    /**
     * Create an instance of {@link NAMESPELLKINDType }
     * 
     */
    public NAMESPELLKINDType createNAMESPELLKINDType() {
        return new NAMESPELLKINDType();
    }

    /**
     * Create an instance of {@link NAMESATTRIBUTEType }
     * 
     */
    public NAMESATTRIBUTEType createNAMESATTRIBUTEType() {
        return new NAMESATTRIBUTEType();
    }

    /**
     * Create an instance of {@link TranslationlabelType }
     * 
     */
    public TranslationlabelType createTranslationlabelType() {
        return new TranslationlabelType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TranslationlabelType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://earthdawn.com/translation", name = "LABEL", scope = TRANSLATIONType.class)
    public JAXBElement<TranslationlabelType> createTRANSLATIONTypeLABEL(TranslationlabelType value) {
        return new JAXBElement<TranslationlabelType>(_TRANSLATIONTypeLABEL_QNAME, TranslationlabelType.class, TRANSLATIONType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TranslationlabelType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://earthdawn.com/translation", name = "SHORTCUT", scope = TRANSLATIONType.class)
    public JAXBElement<TranslationlabelType> createTRANSLATIONTypeSHORTCUT(TranslationlabelType value) {
        return new JAXBElement<TranslationlabelType>(_TRANSLATIONTypeSHORTCUT_QNAME, TranslationlabelType.class, TRANSLATIONType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CHARACTERISTICSSTEPDICETABLE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://earthdawn.com/characteristics", name = "STEPDICETABLE", scope = CHARACTERISTICS.class)
    public JAXBElement<CHARACTERISTICSSTEPDICETABLE> createCHARACTERISTICSSTEPDICETABLE(CHARACTERISTICSSTEPDICETABLE value) {
        return new JAXBElement<CHARACTERISTICSSTEPDICETABLE>(_CHARACTERISTICSSTEPDICETABLE_QNAME, CHARACTERISTICSSTEPDICETABLE.class, CHARACTERISTICS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CHARACTERISTICSDEFENSERAITING }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://earthdawn.com/characteristics", name = "DEFENSERAITING", scope = CHARACTERISTICS.class)
    public JAXBElement<CHARACTERISTICSDEFENSERAITING> createCHARACTERISTICSDEFENSERAITING(CHARACTERISTICSDEFENSERAITING value) {
        return new JAXBElement<CHARACTERISTICSDEFENSERAITING>(_CHARACTERISTICSDEFENSERAITING_QNAME, CHARACTERISTICSDEFENSERAITING.class, CHARACTERISTICS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CHARACTERISTICSENCUMBRANCE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://earthdawn.com/characteristics", name = "ENCUMBRANCE", scope = CHARACTERISTICS.class)
    public JAXBElement<CHARACTERISTICSENCUMBRANCE> createCHARACTERISTICSENCUMBRANCE(CHARACTERISTICSENCUMBRANCE value) {
        return new JAXBElement<CHARACTERISTICSENCUMBRANCE>(_CHARACTERISTICSENCUMBRANCE_QNAME, CHARACTERISTICSENCUMBRANCE.class, CHARACTERISTICS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CHARACTERISTICSDISCIPLINENR }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://earthdawn.com/characteristics", name = "DISCIPLINENR", scope = CHARACTERISTICS.class)
    public JAXBElement<CHARACTERISTICSDISCIPLINENR> createCHARACTERISTICSDISCIPLINENR(CHARACTERISTICSDISCIPLINENR value) {
        return new JAXBElement<CHARACTERISTICSDISCIPLINENR>(_CHARACTERISTICSDISCIPLINENR_QNAME, CHARACTERISTICSDISCIPLINENR.class, CHARACTERISTICS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CHARACTERISTICSNEWDISCIPLINETALENTCOST }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://earthdawn.com/characteristics", name = "NEWDISCIPLINETALENTCOST", scope = CHARACTERISTICS.class)
    public JAXBElement<CHARACTERISTICSNEWDISCIPLINETALENTCOST> createCHARACTERISTICSNEWDISCIPLINETALENTCOST(CHARACTERISTICSNEWDISCIPLINETALENTCOST value) {
        return new JAXBElement<CHARACTERISTICSNEWDISCIPLINETALENTCOST>(_CHARACTERISTICSNEWDISCIPLINETALENTCOST_QNAME, CHARACTERISTICSNEWDISCIPLINETALENTCOST.class, CHARACTERISTICS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CHARACTERISTICSRESULTLEVEL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://earthdawn.com/characteristics", name = "RESULTLEVEL", scope = CHARACTERISTICS.class)
    public JAXBElement<CHARACTERISTICSRESULTLEVEL> createCHARACTERISTICSRESULTLEVEL(CHARACTERISTICSRESULTLEVEL value) {
        return new JAXBElement<CHARACTERISTICSRESULTLEVEL>(_CHARACTERISTICSRESULTLEVEL_QNAME, CHARACTERISTICSRESULTLEVEL.class, CHARACTERISTICS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CHARACTERISTICSHEALTHRATING }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://earthdawn.com/characteristics", name = "HEALTHRATING", scope = CHARACTERISTICS.class)
    public JAXBElement<CHARACTERISTICSHEALTHRATING> createCHARACTERISTICSHEALTHRATING(CHARACTERISTICSHEALTHRATING value) {
        return new JAXBElement<CHARACTERISTICSHEALTHRATING>(_CHARACTERISTICSHEALTHRATING_QNAME, CHARACTERISTICSHEALTHRATING.class, CHARACTERISTICS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CHARACTERISTICSLEGENDARYSTATUS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://earthdawn.com/characteristics", name = "LEGENDARYSTATUS", scope = CHARACTERISTICS.class)
    public JAXBElement<CHARACTERISTICSLEGENDARYSTATUS> createCHARACTERISTICSLEGENDARYSTATUS(CHARACTERISTICSLEGENDARYSTATUS value) {
        return new JAXBElement<CHARACTERISTICSLEGENDARYSTATUS>(_CHARACTERISTICSLEGENDARYSTATUS_QNAME, CHARACTERISTICSLEGENDARYSTATUS.class, CHARACTERISTICS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CHARACTERISTICSCOST }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://earthdawn.com/characteristics", name = "ATTRIBUTELPCOST", scope = CHARACTERISTICS.class)
    public JAXBElement<CHARACTERISTICSCOST> createCHARACTERISTICSATTRIBUTELPCOST(CHARACTERISTICSCOST value) {
        return new JAXBElement<CHARACTERISTICSCOST>(_CHARACTERISTICSATTRIBUTELPCOST_QNAME, CHARACTERISTICSCOST.class, CHARACTERISTICS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CHARACTERISTICSMYSTICARMOR }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://earthdawn.com/characteristics", name = "MYSTICARMOR", scope = CHARACTERISTICS.class)
    public JAXBElement<CHARACTERISTICSMYSTICARMOR> createCHARACTERISTICSMYSTICARMOR(CHARACTERISTICSMYSTICARMOR value) {
        return new JAXBElement<CHARACTERISTICSMYSTICARMOR>(_CHARACTERISTICSMYSTICARMOR_QNAME, CHARACTERISTICSMYSTICARMOR.class, CHARACTERISTICS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CHARACTERISTICSATTRIBUTECOST }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://earthdawn.com/characteristics", name = "ATTRIBUTECOST", scope = CHARACTERISTICS.class)
    public JAXBElement<CHARACTERISTICSATTRIBUTECOST> createCHARACTERISTICSATTRIBUTECOST(CHARACTERISTICSATTRIBUTECOST value) {
        return new JAXBElement<CHARACTERISTICSATTRIBUTECOST>(_CHARACTERISTICSATTRIBUTECOST_QNAME, CHARACTERISTICSATTRIBUTECOST.class, CHARACTERISTICS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CHARACTERISTICSCOST }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://earthdawn.com/characteristics", name = "SKILLLPCOST", scope = CHARACTERISTICS.class)
    public JAXBElement<CHARACTERISTICSCOST> createCHARACTERISTICSSKILLLPCOST(CHARACTERISTICSCOST value) {
        return new JAXBElement<CHARACTERISTICSCOST>(_CHARACTERISTICSSKILLLPCOST_QNAME, CHARACTERISTICSCOST.class, CHARACTERISTICS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CAPABILITYType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://earthdawn.com/capability", name = "SKILL", scope = CAPABILITIES.class)
    public JAXBElement<CAPABILITYType> createCAPABILITIESSKILL(CAPABILITYType value) {
        return new JAXBElement<CAPABILITYType>(_CAPABILITIESSKILL_QNAME, CAPABILITYType.class, CAPABILITIES.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CAPABILITYType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://earthdawn.com/capability", name = "TALENT", scope = CAPABILITIES.class)
    public JAXBElement<CAPABILITYType> createCAPABILITIESTALENT(CAPABILITYType value) {
        return new JAXBElement<CAPABILITYType>(_CAPABILITIESTALENT_QNAME, CAPABILITYType.class, CAPABILITIES.class, value);
    }

}
