//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: see version control commit date
//


package de.earthdawn.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OPTIONALRULES_DEFAULTOPTIONALTALENT complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="OPTIONALRULES_DEFAULTOPTIONALTALENT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="talent" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="circle" use="required" type="{http://earthdawn.com/datatypes}unsigned_int" /&gt;
 *       &lt;attribute name="lang" use="required" type="{http://earthdawn.com/datatypes}language_type" /&gt;
 *       &lt;attribute name="discipline" type="{http://earthdawn.com/datatypes}unsigned_int" default="1" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OPTIONALRULES_DEFAULTOPTIONALTALENT", namespace = "http://earthdawn.com/optionalrules")
public class OPTIONALRULESDEFAULTOPTIONALTALENT {

    @XmlAttribute(name = "talent", required = true)
    protected String talent;
    @XmlAttribute(name = "circle", required = true)
    protected int circle;
    @XmlAttribute(name = "lang", required = true)
    protected LanguageType lang;
    @XmlAttribute(name = "discipline")
    protected Integer discipline;

    /**
     * Gets the value of the talent property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTalent() {
        return talent;
    }

    /**
     * Sets the value of the talent property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTalent(String value) {
        this.talent = value;
    }

    /**
     * Gets the value of the circle property.
     *
     */
    public int getCircle() {
        return circle;
    }

    /**
     * Sets the value of the circle property.
     *
     */
    public void setCircle(int value) {
        this.circle = value;
    }

    /**
     * Gets the value of the lang property.
     *
     * @return
     *     possible object is
     *     {@link LanguageType }
     *
     */
    public LanguageType getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     *
     * @param value
     *     allowed object is
     *     {@link LanguageType }
     *
     */
    public void setLang(LanguageType value) {
        this.lang = value;
    }

    /**
     * Gets the value of the discipline property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public int getDiscipline() {
        if (discipline == null) {
            return  1;
        } else {
            return discipline;
        }
    }

    /**
     * Sets the value of the discipline property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setDiscipline(Integer value) {
        this.discipline = value;
    }

}
