//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: see version control commit date
//


package de.earthdawn.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PATH_type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PATH_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PATHBONUS" type="{http://earthdawn.com/datatypes}DISCIPLINEBONUS_type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="KARMARITUAL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="HALFMAGIC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TALENT" type="{http://earthdawn.com/datatypes}TALENT_type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="rank" use="required" type="{http://earthdawn.com/datatypes}circle_type" /&gt;
 *       &lt;attribute name="knack" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PATH_type", propOrder = {
    "pathbonus",
    "karmaritual",
    "halfmagic",
    "talent"
})
public class PATHType {

    @XmlElement(name = "PATHBONUS")
    protected List<DISCIPLINEBONUSType> pathbonus;
    @XmlElement(name = "KARMARITUAL")
    protected String karmaritual;
    @XmlElement(name = "HALFMAGIC")
    protected String halfmagic;
    @XmlElement(name = "TALENT")
    protected List<TALENTType> talent;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "rank", required = true)
    protected int rank;
    @XmlAttribute(name = "knack", required = true)
    protected String knack;

    /**
     * Gets the value of the pathbonus property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pathbonus property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPATHBONUS().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DISCIPLINEBONUSType }
     *
     *
     */
    public List<DISCIPLINEBONUSType> getPATHBONUS() {
        if (pathbonus == null) {
            pathbonus = new ArrayList<DISCIPLINEBONUSType>();
        }
        return this.pathbonus;
    }

    /**
     * Gets the value of the karmaritual property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKARMARITUAL() {
        return karmaritual;
    }

    /**
     * Sets the value of the karmaritual property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKARMARITUAL(String value) {
        this.karmaritual = value;
    }

    /**
     * Gets the value of the halfmagic property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHALFMAGIC() {
        return halfmagic;
    }

    /**
     * Sets the value of the halfmagic property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHALFMAGIC(String value) {
        this.halfmagic = value;
    }

    /**
     * Gets the value of the talent property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the talent property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTALENT().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TALENTType }
     *
     *
     */
    public List<TALENTType> getTALENT() {
        if (talent == null) {
            talent = new ArrayList<TALENTType>();
        }
        return this.talent;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the rank property.
     *
     */
    public int getRank() {
        return rank;
    }

    /**
     * Sets the value of the rank property.
     *
     */
    public void setRank(int value) {
        this.rank = value;
    }

    /**
     * Gets the value of the knack property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKnack() {
        return knack;
    }

    /**
     * Sets the value of the knack property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKnack(String value) {
        this.knack = value;
    }

}
