//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: see version control commit date
//


package de.earthdawn.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PATHTALENT_type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PATHTALENT_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="tier" use="required" type="{http://earthdawn.com/datatypes}tierkind_type" /&gt;
 *       &lt;attribute name="maxrank" use="required" type="{http://earthdawn.com/datatypes}unsigned_int" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PATHTALENT_type", namespace = "http://earthdawn.com/path")
public class PATHTALENTType {

    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "tier", required = true)
    protected TierkindType tier;
    @XmlAttribute(name = "maxrank", required = true)
    protected int maxrank;

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the tier property.
     *
     * @return
     *     possible object is
     *     {@link TierkindType }
     *
     */
    public TierkindType getTier() {
        return tier;
    }

    /**
     * Sets the value of the tier property.
     *
     * @param value
     *     allowed object is
     *     {@link TierkindType }
     *
     */
    public void setTier(TierkindType value) {
        this.tier = value;
    }

    /**
     * Gets the value of the maxrank property.
     *
     */
    public int getMaxrank() {
        return maxrank;
    }

    /**
     * Sets the value of the maxrank property.
     *
     */
    public void setMaxrank(int value) {
        this.maxrank = value;
    }

}
