//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: see version control commit date
//


package de.earthdawn.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RANKHISTORY_type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RANKHISTORY_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="rank" use="required" type="{http://earthdawn.com/datatypes}unsigned_int" /&gt;
 *       &lt;attribute name="mincircle" use="required" type="{http://earthdawn.com/datatypes}circle_type" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RANKHISTORY_type")
public class RANKHISTORYType {

    @XmlAttribute(name = "rank", required = true)
    protected int rank;
    @XmlAttribute(name = "mincircle", required = true)
    protected int mincircle;

    /**
     * Gets the value of the rank property.
     *
     */
    public int getRank() {
        return rank;
    }

    /**
     * Sets the value of the rank property.
     *
     */
    public void setRank(int value) {
        this.rank = value;
    }

    /**
     * Gets the value of the mincircle property.
     *
     */
    public int getMincircle() {
        return mincircle;
    }

    /**
     * Sets the value of the mincircle property.
     *
     */
    public void setMincircle(int value) {
        this.mincircle = value;
    }

}
