//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.26 at 10:48:51 PM MESZ 
//


package de.earthdawn.data;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RUESTUNG_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RUESTUNG_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="bezeichnung" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="gewicht" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="aktiv" use="required" type="{http://earthdawn.de}janein_type" />
 *       &lt;attribute name="behinderung" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="bruchschwelle" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="mystisch" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="physikalisch" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ort" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RUESTUNG_type")
public class RUESTUNGType {

    @XmlAttribute(required = true)
    protected String bezeichnung;
    @XmlAttribute(required = true)
    protected BigDecimal gewicht;
    @XmlAttribute(required = true)
    protected JaneinType aktiv;
    @XmlAttribute(required = true)
    protected BigInteger behinderung;
    @XmlAttribute(required = true)
    protected BigInteger bruchschwelle;
    @XmlAttribute(required = true)
    protected BigInteger mystisch;
    @XmlAttribute(required = true)
    protected BigInteger physikalisch;
    @XmlAttribute(required = true)
    protected String ort;

    /**
     * Gets the value of the bezeichnung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBezeichnung() {
        return bezeichnung;
    }

    /**
     * Sets the value of the bezeichnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBezeichnung(String value) {
        this.bezeichnung = value;
    }

    /**
     * Gets the value of the gewicht property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGewicht() {
        return gewicht;
    }

    /**
     * Sets the value of the gewicht property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGewicht(BigDecimal value) {
        this.gewicht = value;
    }

    /**
     * Gets the value of the aktiv property.
     * 
     * @return
     *     possible object is
     *     {@link JaneinType }
     *     
     */
    public JaneinType getAktiv() {
        return aktiv;
    }

    /**
     * Sets the value of the aktiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link JaneinType }
     *     
     */
    public void setAktiv(JaneinType value) {
        this.aktiv = value;
    }

    /**
     * Gets the value of the behinderung property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBehinderung() {
        return behinderung;
    }

    /**
     * Sets the value of the behinderung property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBehinderung(BigInteger value) {
        this.behinderung = value;
    }

    /**
     * Gets the value of the bruchschwelle property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBruchschwelle() {
        return bruchschwelle;
    }

    /**
     * Sets the value of the bruchschwelle property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBruchschwelle(BigInteger value) {
        this.bruchschwelle = value;
    }

    /**
     * Gets the value of the mystisch property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMystisch() {
        return mystisch;
    }

    /**
     * Sets the value of the mystisch property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMystisch(BigInteger value) {
        this.mystisch = value;
    }

    /**
     * Gets the value of the physikalisch property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPhysikalisch() {
        return physikalisch;
    }

    /**
     * Sets the value of the physikalisch property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPhysikalisch(BigInteger value) {
        this.physikalisch = value;
    }

    /**
     * Gets the value of the ort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrt() {
        return ort;
    }

    /**
     * Sets the value of the ort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrt(String value) {
        this.ort = value;
    }

}
