//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: see version control commit date
//


package de.earthdawn.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SKILL_type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SKILL_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://earthdawn.com/datatypes}CAPABILITY_type"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RANK" type="{http://earthdawn.com/datatypes}RANK_type"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SKILL_type", propOrder = {
    "rank"
})
@XmlSeeAlso({
    TALENTType.class
})
public class SKILLType
    extends CAPABILITYType
{

    @XmlElement(name = "RANK", required = true)
    protected RANKType rank;

    /**
     * Gets the value of the rank property.
     *
     * @return
     *     possible object is
     *     {@link RANKType }
     *
     */
    public RANKType getRANK() {
        return rank;
    }

    /**
     * Sets the value of the rank property.
     *
     * @param value
     *     allowed object is
     *     {@link RANKType }
     *
     */
    public void setRANK(RANKType value) {
        this.rank = value;
    }

}
