//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: see version control commit date
//


package de.earthdawn.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SPELLDEF_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SPELLDEF_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="threads" use="required" type="{http://earthdawn.com/datatypes}unsigned_int" />
 *       &lt;attribute name="weavingdifficulty" use="required" type="{http://earthdawn.com/datatypes}unsigned_int" />
 *       &lt;attribute name="reattuningdifficulty" use="required" type="{http://earthdawn.com/datatypes}unsigned_int" />
 *       &lt;attribute name="castingdifficulty" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="range" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="duration" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="effect" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SPELLDEF_type")
@XmlSeeAlso({
    SPELLType.class
})
public class SPELLDEFType {

    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(required = true)
    protected int threads;
    @XmlAttribute(required = true)
    protected int weavingdifficulty;
    @XmlAttribute(required = true)
    protected int reattuningdifficulty;
    @XmlAttribute(required = true)
    protected String castingdifficulty;
    @XmlAttribute(required = true)
    protected String range;
    @XmlAttribute(required = true)
    protected String duration;
    @XmlAttribute(required = true)
    protected String effect;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the threads property.
     * 
     */
    public int getThreads() {
        return threads;
    }

    /**
     * Sets the value of the threads property.
     * 
     */
    public void setThreads(int value) {
        this.threads = value;
    }

    /**
     * Gets the value of the weavingdifficulty property.
     * 
     */
    public int getWeavingdifficulty() {
        return weavingdifficulty;
    }

    /**
     * Sets the value of the weavingdifficulty property.
     * 
     */
    public void setWeavingdifficulty(int value) {
        this.weavingdifficulty = value;
    }

    /**
     * Gets the value of the reattuningdifficulty property.
     * 
     */
    public int getReattuningdifficulty() {
        return reattuningdifficulty;
    }

    /**
     * Sets the value of the reattuningdifficulty property.
     * 
     */
    public void setReattuningdifficulty(int value) {
        this.reattuningdifficulty = value;
    }

    /**
     * Gets the value of the castingdifficulty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCastingdifficulty() {
        return castingdifficulty;
    }

    /**
     * Sets the value of the castingdifficulty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCastingdifficulty(String value) {
        this.castingdifficulty = value;
    }

    /**
     * Gets the value of the range property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRange() {
        return range;
    }

    /**
     * Sets the value of the range property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRange(String value) {
        this.range = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuration(String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the effect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffect() {
        return effect;
    }

    /**
     * Sets the value of the effect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffect(String value) {
        this.effect = value;
    }

}
