//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.09 at 08:12:32 PM MEZ 
//


package de.earthdawn.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for spelltype_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="spelltype_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="elemental"/>
 *     &lt;enumeration value="nether"/>
 *     &lt;enumeration value="illusion"/>
 *     &lt;enumeration value="wizard"/>
 *     &lt;enumeration value="shamane"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "spelltype_type")
@XmlEnum
public enum SpelltypeType {

    @XmlEnumValue("elemental")
    ELEMENTAL("elemental"),
    @XmlEnumValue("nether")
    NETHER("nether"),
    @XmlEnumValue("illusion")
    ILLUSION("illusion"),
    @XmlEnumValue("wizard")
    WIZARD("wizard"),
    @XmlEnumValue("shamane")
    SHAMANE("shamane");
    private final String value;

    SpelltypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SpelltypeType fromValue(String v) {
        for (SpelltypeType c: SpelltypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
