//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.07 at 08:00:39 PM MEZ 
//


package de.earthdawn.data;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SPELL_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SPELL_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="inmatrix" use="required" type="{http://earthdawn.com}yesno_type" />
 *       &lt;attribute name="type" use="required" type="{http://earthdawn.com}spelltype_type" />
 *       &lt;attribute name="circle" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="threads" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="weavingdifficulty" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="castingdifficulty" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="range" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="duration" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="effect" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SPELL_type")
public class SPELLType {

    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(required = true)
    protected YesnoType inmatrix;
    @XmlAttribute(required = true)
    protected SpelltypeType type;
    @XmlAttribute(required = true)
    protected BigInteger circle;
    @XmlAttribute(required = true)
    protected BigInteger threads;
    @XmlAttribute(required = true)
    protected String weavingdifficulty;
    @XmlAttribute(required = true)
    protected String castingdifficulty;
    @XmlAttribute(required = true)
    protected String range;
    @XmlAttribute(required = true)
    protected String duration;
    @XmlAttribute(required = true)
    protected String effect;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the inmatrix property.
     * 
     * @return
     *     possible object is
     *     {@link YesnoType }
     *     
     */
    public YesnoType getInmatrix() {
        return inmatrix;
    }

    /**
     * Sets the value of the inmatrix property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesnoType }
     *     
     */
    public void setInmatrix(YesnoType value) {
        this.inmatrix = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link SpelltypeType }
     *     
     */
    public SpelltypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpelltypeType }
     *     
     */
    public void setType(SpelltypeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the circle property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCircle() {
        return circle;
    }

    /**
     * Sets the value of the circle property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCircle(BigInteger value) {
        this.circle = value;
    }

    /**
     * Gets the value of the threads property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getThreads() {
        return threads;
    }

    /**
     * Sets the value of the threads property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setThreads(BigInteger value) {
        this.threads = value;
    }

    /**
     * Gets the value of the weavingdifficulty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeavingdifficulty() {
        return weavingdifficulty;
    }

    /**
     * Sets the value of the weavingdifficulty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeavingdifficulty(String value) {
        this.weavingdifficulty = value;
    }

    /**
     * Gets the value of the castingdifficulty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCastingdifficulty() {
        return castingdifficulty;
    }

    /**
     * Sets the value of the castingdifficulty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCastingdifficulty(String value) {
        this.castingdifficulty = value;
    }

    /**
     * Gets the value of the range property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRange() {
        return range;
    }

    /**
     * Sets the value of the range property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRange(String value) {
        this.range = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuration(String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the effect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffect() {
        return effect;
    }

    /**
     * Sets the value of the effect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffect(String value) {
        this.effect = value;
    }

}
