//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: see version control commit date
//


package de.earthdawn.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TALENT_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TALENT_type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://earthdawn.com/datatypes}SKILL_type">
 *       &lt;sequence>
 *         &lt;element name="TEACHER" type="{http://earthdawn.com/datatypes}TALENTTEACHER_type"/>
 *       &lt;/sequence>
 *       &lt;attribute name="circle" use="required" type="{http://earthdawn.com/datatypes}circle_type" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TALENT_type", propOrder = {
    "teacher"
})
public class TALENTType
    extends SKILLType
{

    @XmlElement(name = "TEACHER", required = true)
    protected TALENTTEACHERType teacher;
    @XmlAttribute(required = true)
    protected int circle;

    /**
     * Gets the value of the teacher property.
     * 
     * @return
     *     possible object is
     *     {@link TALENTTEACHERType }
     *     
     */
    public TALENTTEACHERType getTEACHER() {
        return teacher;
    }

    /**
     * Sets the value of the teacher property.
     * 
     * @param value
     *     allowed object is
     *     {@link TALENTTEACHERType }
     *     
     */
    public void setTEACHER(TALENTTEACHERType value) {
        this.teacher = value;
    }

    /**
     * Gets the value of the circle property.
     * 
     */
    public int getCircle() {
        return circle;
    }

    /**
     * Sets the value of the circle property.
     * 
     */
    public void setCircle(int value) {
        this.circle = value;
    }

}
