//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: see version control commit date
//


package de.earthdawn.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tierkind_type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tierkind_type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="auto"/&gt;
 *     &lt;enumeration value="novice"/&gt;
 *     &lt;enumeration value="journeyman"/&gt;
 *     &lt;enumeration value="warden"/&gt;
 *     &lt;enumeration value="master"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "tierkind_type")
@XmlEnum
public enum TierkindType {

    @XmlEnumValue("auto")
    AUTO("auto"),
    @XmlEnumValue("novice")
    NOVICE("novice"),
    @XmlEnumValue("journeyman")
    JOURNEYMAN("journeyman"),
    @XmlEnumValue("warden")
    WARDEN("warden"),
    @XmlEnumValue("master")
    MASTER("master");
    private final String value;

    TierkindType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TierkindType fromValue(String v) {
        for (TierkindType c: TierkindType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
