//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: see version control commit date
//


package de.earthdawn.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ATTRIBUTES" type="{http://earthdawn.com/translation}NAMES_ATTRIBUTES_type" maxOccurs="unbounded"/&gt;
 *         &lt;element name="ACTIONS" type="{http://earthdawn.com/translation}NAMES_ACTIONS_type" maxOccurs="unbounded"/&gt;
 *         &lt;element name="DURABILITY" type="{http://earthdawn.com/translation}TRANSLATION_type" maxOccurs="unbounded"/&gt;
 *         &lt;element name="VERSATILITY" type="{http://earthdawn.com/translation}TRANSLATION_type" maxOccurs="unbounded"/&gt;
 *         &lt;element name="KARMARUTUAL" type="{http://earthdawn.com/translation}TRANSLATION_type" maxOccurs="unbounded"/&gt;
 *         &lt;element name="ARTISAN" type="{http://earthdawn.com/translation}TRANSLATION_type" maxOccurs="unbounded"/&gt;
 *         &lt;element name="KNOWLEDGE" type="{http://earthdawn.com/translation}TRANSLATION_type" maxOccurs="unbounded"/&gt;
 *         &lt;element name="QUESTORTALENT" type="{http://earthdawn.com/translation}TRANSLATION_type" maxOccurs="unbounded"/&gt;
 *         &lt;element name="THREADWEAVING" type="{http://earthdawn.com/translation}TRANSLATION_type" maxOccurs="unbounded"/&gt;
 *         &lt;element name="LANGUAGESKILLSPEAK" type="{http://earthdawn.com/translation}TRANSLATION_type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="LANGUAGESKILLREADWRITE" type="{http://earthdawn.com/translation}TRANSLATION_type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="DISCIPLINETIER" type="{http://earthdawn.com/translation}NAME_TIERKIND_type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="QUESTORTIER" type="{http://earthdawn.com/translation}NAME_TIERKIND_type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="SPELLWEAVING" type="{http://earthdawn.com/translation}NAME_SPELLWEAVING_type" maxOccurs="unbounded"/&gt;
 *         &lt;element name="CAPABILITY" type="{http://earthdawn.com/translation}TRANSLATION_type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="SPELL" type="{http://earthdawn.com/translation}TRANSLATION_type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="DISCIPLINE" type="{http://earthdawn.com/translation}TRANSLATION_type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="NAMEGIVER" type="{http://earthdawn.com/translation}TRANSLATION_type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ITEM" type="{http://earthdawn.com/translation}TRANSLATION_type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="APPEARANCE" type="{http://earthdawn.com/translation}GENERALTEXT_type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="HEALTH" type="{http://earthdawn.com/translation}GENERALTEXT_type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="TEXT" type="{http://earthdawn.com/translation}GENERALTEXT_type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="rulesetversion" use="required" type="{http://earthdawn.com/datatypes}rulesetversion_type" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attributes",
    "actions",
    "durability",
    "versatility",
    "karmarutual",
    "artisan",
    "knowledge",
    "questortalent",
    "threadweaving",
    "languageskillspeak",
    "languageskillreadwrite",
    "disciplinetier",
    "questortier",
    "spellweaving",
    "capability",
    "spell",
    "discipline",
    "namegiver",
    "item",
    "appearance",
    "health",
    "text"
})
@XmlRootElement(name = "TRANSLATIONS", namespace = "http://earthdawn.com/translation")
public class TRANSLATIONS {

    @XmlElement(name = "ATTRIBUTES", namespace = "http://earthdawn.com/translation", required = true)
    protected List<NAMESATTRIBUTESType> attributes;
    @XmlElement(name = "ACTIONS", namespace = "http://earthdawn.com/translation", required = true)
    protected List<NAMESACTIONSType> actions;
    @XmlElement(name = "DURABILITY", namespace = "http://earthdawn.com/translation", required = true)
    protected List<TRANSLATIONType> durability;
    @XmlElement(name = "VERSATILITY", namespace = "http://earthdawn.com/translation", required = true)
    protected List<TRANSLATIONType> versatility;
    @XmlElement(name = "KARMARUTUAL", namespace = "http://earthdawn.com/translation", required = true)
    protected List<TRANSLATIONType> karmarutual;
    @XmlElement(name = "ARTISAN", namespace = "http://earthdawn.com/translation", required = true)
    protected List<TRANSLATIONType> artisan;
    @XmlElement(name = "KNOWLEDGE", namespace = "http://earthdawn.com/translation", required = true)
    protected List<TRANSLATIONType> knowledge;
    @XmlElement(name = "QUESTORTALENT", namespace = "http://earthdawn.com/translation", required = true)
    protected List<TRANSLATIONType> questortalent;
    @XmlElement(name = "THREADWEAVING", namespace = "http://earthdawn.com/translation", required = true)
    protected List<TRANSLATIONType> threadweaving;
    @XmlElement(name = "LANGUAGESKILLSPEAK", namespace = "http://earthdawn.com/translation")
    protected List<TRANSLATIONType> languageskillspeak;
    @XmlElement(name = "LANGUAGESKILLREADWRITE", namespace = "http://earthdawn.com/translation")
    protected List<TRANSLATIONType> languageskillreadwrite;
    @XmlElement(name = "DISCIPLINETIER", namespace = "http://earthdawn.com/translation")
    protected List<NAMETIERKINDType> disciplinetier;
    @XmlElement(name = "QUESTORTIER", namespace = "http://earthdawn.com/translation")
    protected List<NAMETIERKINDType> questortier;
    @XmlElement(name = "SPELLWEAVING", namespace = "http://earthdawn.com/translation", required = true)
    protected List<NAMESPELLWEAVINGType> spellweaving;
    @XmlElement(name = "CAPABILITY", namespace = "http://earthdawn.com/translation")
    protected List<TRANSLATIONType> capability;
    @XmlElement(name = "SPELL", namespace = "http://earthdawn.com/translation")
    protected List<TRANSLATIONType> spell;
    @XmlElement(name = "DISCIPLINE", namespace = "http://earthdawn.com/translation")
    protected List<TRANSLATIONType> discipline;
    @XmlElement(name = "NAMEGIVER", namespace = "http://earthdawn.com/translation")
    protected List<TRANSLATIONType> namegiver;
    @XmlElement(name = "ITEM", namespace = "http://earthdawn.com/translation")
    protected List<TRANSLATIONType> item;
    @XmlElement(name = "APPEARANCE", namespace = "http://earthdawn.com/translation")
    protected List<GENERALTEXTType> appearance;
    @XmlElement(name = "HEALTH", namespace = "http://earthdawn.com/translation")
    protected List<GENERALTEXTType> health;
    @XmlElement(name = "TEXT", namespace = "http://earthdawn.com/translation")
    protected List<GENERALTEXTType> text;
    @XmlAttribute(name = "rulesetversion", required = true)
    protected RulesetversionType rulesetversion;

    /**
     * Gets the value of the attributes property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributes property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getATTRIBUTES().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NAMESATTRIBUTESType }
     *
     *
     */
    public List<NAMESATTRIBUTESType> getATTRIBUTES() {
        if (attributes == null) {
            attributes = new ArrayList<NAMESATTRIBUTESType>();
        }
        return this.attributes;
    }

    /**
     * Gets the value of the actions property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actions property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getACTIONS().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NAMESACTIONSType }
     *
     *
     */
    public List<NAMESACTIONSType> getACTIONS() {
        if (actions == null) {
            actions = new ArrayList<NAMESACTIONSType>();
        }
        return this.actions;
    }

    /**
     * Gets the value of the durability property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the durability property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDURABILITY().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRANSLATIONType }
     *
     *
     */
    public List<TRANSLATIONType> getDURABILITY() {
        if (durability == null) {
            durability = new ArrayList<TRANSLATIONType>();
        }
        return this.durability;
    }

    /**
     * Gets the value of the versatility property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the versatility property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVERSATILITY().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRANSLATIONType }
     *
     *
     */
    public List<TRANSLATIONType> getVERSATILITY() {
        if (versatility == null) {
            versatility = new ArrayList<TRANSLATIONType>();
        }
        return this.versatility;
    }

    /**
     * Gets the value of the karmarutual property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the karmarutual property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKARMARUTUAL().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRANSLATIONType }
     *
     *
     */
    public List<TRANSLATIONType> getKARMARUTUAL() {
        if (karmarutual == null) {
            karmarutual = new ArrayList<TRANSLATIONType>();
        }
        return this.karmarutual;
    }

    /**
     * Gets the value of the artisan property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the artisan property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getARTISAN().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRANSLATIONType }
     *
     *
     */
    public List<TRANSLATIONType> getARTISAN() {
        if (artisan == null) {
            artisan = new ArrayList<TRANSLATIONType>();
        }
        return this.artisan;
    }

    /**
     * Gets the value of the knowledge property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the knowledge property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKNOWLEDGE().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRANSLATIONType }
     *
     *
     */
    public List<TRANSLATIONType> getKNOWLEDGE() {
        if (knowledge == null) {
            knowledge = new ArrayList<TRANSLATIONType>();
        }
        return this.knowledge;
    }

    /**
     * Gets the value of the questortalent property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the questortalent property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQUESTORTALENT().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRANSLATIONType }
     *
     *
     */
    public List<TRANSLATIONType> getQUESTORTALENT() {
        if (questortalent == null) {
            questortalent = new ArrayList<TRANSLATIONType>();
        }
        return this.questortalent;
    }

    /**
     * Gets the value of the threadweaving property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the threadweaving property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTHREADWEAVING().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRANSLATIONType }
     *
     *
     */
    public List<TRANSLATIONType> getTHREADWEAVING() {
        if (threadweaving == null) {
            threadweaving = new ArrayList<TRANSLATIONType>();
        }
        return this.threadweaving;
    }

    /**
     * Gets the value of the languageskillspeak property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the languageskillspeak property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLANGUAGESKILLSPEAK().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRANSLATIONType }
     *
     *
     */
    public List<TRANSLATIONType> getLANGUAGESKILLSPEAK() {
        if (languageskillspeak == null) {
            languageskillspeak = new ArrayList<TRANSLATIONType>();
        }
        return this.languageskillspeak;
    }

    /**
     * Gets the value of the languageskillreadwrite property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the languageskillreadwrite property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLANGUAGESKILLREADWRITE().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRANSLATIONType }
     *
     *
     */
    public List<TRANSLATIONType> getLANGUAGESKILLREADWRITE() {
        if (languageskillreadwrite == null) {
            languageskillreadwrite = new ArrayList<TRANSLATIONType>();
        }
        return this.languageskillreadwrite;
    }

    /**
     * Gets the value of the disciplinetier property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the disciplinetier property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDISCIPLINETIER().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NAMETIERKINDType }
     *
     *
     */
    public List<NAMETIERKINDType> getDISCIPLINETIER() {
        if (disciplinetier == null) {
            disciplinetier = new ArrayList<NAMETIERKINDType>();
        }
        return this.disciplinetier;
    }

    /**
     * Gets the value of the questortier property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the questortier property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQUESTORTIER().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NAMETIERKINDType }
     *
     *
     */
    public List<NAMETIERKINDType> getQUESTORTIER() {
        if (questortier == null) {
            questortier = new ArrayList<NAMETIERKINDType>();
        }
        return this.questortier;
    }

    /**
     * Gets the value of the spellweaving property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spellweaving property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSPELLWEAVING().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NAMESPELLWEAVINGType }
     *
     *
     */
    public List<NAMESPELLWEAVINGType> getSPELLWEAVING() {
        if (spellweaving == null) {
            spellweaving = new ArrayList<NAMESPELLWEAVINGType>();
        }
        return this.spellweaving;
    }

    /**
     * Gets the value of the capability property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the capability property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCAPABILITY().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRANSLATIONType }
     *
     *
     */
    public List<TRANSLATIONType> getCAPABILITY() {
        if (capability == null) {
            capability = new ArrayList<TRANSLATIONType>();
        }
        return this.capability;
    }

    /**
     * Gets the value of the spell property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spell property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSPELL().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRANSLATIONType }
     *
     *
     */
    public List<TRANSLATIONType> getSPELL() {
        if (spell == null) {
            spell = new ArrayList<TRANSLATIONType>();
        }
        return this.spell;
    }

    /**
     * Gets the value of the discipline property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the discipline property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDISCIPLINE().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRANSLATIONType }
     *
     *
     */
    public List<TRANSLATIONType> getDISCIPLINE() {
        if (discipline == null) {
            discipline = new ArrayList<TRANSLATIONType>();
        }
        return this.discipline;
    }

    /**
     * Gets the value of the namegiver property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the namegiver property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNAMEGIVER().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRANSLATIONType }
     *
     *
     */
    public List<TRANSLATIONType> getNAMEGIVER() {
        if (namegiver == null) {
            namegiver = new ArrayList<TRANSLATIONType>();
        }
        return this.namegiver;
    }

    /**
     * Gets the value of the item property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getITEM().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRANSLATIONType }
     *
     *
     */
    public List<TRANSLATIONType> getITEM() {
        if (item == null) {
            item = new ArrayList<TRANSLATIONType>();
        }
        return this.item;
    }

    /**
     * Gets the value of the appearance property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the appearance property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAPPEARANCE().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GENERALTEXTType }
     *
     *
     */
    public List<GENERALTEXTType> getAPPEARANCE() {
        if (appearance == null) {
            appearance = new ArrayList<GENERALTEXTType>();
        }
        return this.appearance;
    }

    /**
     * Gets the value of the health property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the health property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHEALTH().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GENERALTEXTType }
     *
     *
     */
    public List<GENERALTEXTType> getHEALTH() {
        if (health == null) {
            health = new ArrayList<GENERALTEXTType>();
        }
        return this.health;
    }

    /**
     * Gets the value of the text property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the text property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTEXT().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GENERALTEXTType }
     *
     *
     */
    public List<GENERALTEXTType> getTEXT() {
        if (text == null) {
            text = new ArrayList<GENERALTEXTType>();
        }
        return this.text;
    }

    /**
     * Gets the value of the rulesetversion property.
     *
     * @return
     *     possible object is
     *     {@link RulesetversionType }
     *
     */
    public RulesetversionType getRulesetversion() {
        return rulesetversion;
    }

    /**
     * Sets the value of the rulesetversion property.
     *
     * @param value
     *     allowed object is
     *     {@link RulesetversionType }
     *
     */
    public void setRulesetversion(RulesetversionType value) {
        this.rulesetversion = value;
    }

}
