//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.25 at 10:51:50 AM MEZ 
//


package de.earthdawn.data;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WEAPON_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WEAPON_type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://earthdawn.de}ITEM_type">
 *       &lt;attribute name="damagestep" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="strengthmin" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="size" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="timesforged" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="shortrange" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="mediumrange" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="longrange" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WEAPON_type")
public class WEAPONType
    extends ITEMType
{

    @XmlAttribute(required = true)
    protected BigInteger damagestep;
    @XmlAttribute(required = true)
    protected BigInteger strengthmin;
    @XmlAttribute(required = true)
    protected BigInteger size;
    @XmlAttribute(required = true)
    protected BigInteger timesforged;
    @XmlAttribute
    protected BigInteger shortrange;
    @XmlAttribute
    protected BigInteger mediumrange;
    @XmlAttribute
    protected BigInteger longrange;

    /**
     * Gets the value of the damagestep property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDamagestep() {
        return damagestep;
    }

    /**
     * Sets the value of the damagestep property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDamagestep(BigInteger value) {
        this.damagestep = value;
    }

    /**
     * Gets the value of the strengthmin property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStrengthmin() {
        return strengthmin;
    }

    /**
     * Sets the value of the strengthmin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStrengthmin(BigInteger value) {
        this.strengthmin = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSize(BigInteger value) {
        this.size = value;
    }

    /**
     * Gets the value of the timesforged property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTimesforged() {
        return timesforged;
    }

    /**
     * Sets the value of the timesforged property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTimesforged(BigInteger value) {
        this.timesforged = value;
    }

    /**
     * Gets the value of the shortrange property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getShortrange() {
        return shortrange;
    }

    /**
     * Sets the value of the shortrange property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setShortrange(BigInteger value) {
        this.shortrange = value;
    }

    /**
     * Gets the value of the mediumrange property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMediumrange() {
        return mediumrange;
    }

    /**
     * Sets the value of the mediumrange property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMediumrange(BigInteger value) {
        this.mediumrange = value;
    }

    /**
     * Gets the value of the longrange property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLongrange() {
        return longrange;
    }

    /**
     * Sets the value of the longrange property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLongrange(BigInteger value) {
        this.longrange = value;
    }

}
