//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.01 at 11:44:24 AM MEZ 
//


package de.earthdawn.data;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZAUBER_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZAUBER_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="bezeichnung" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="effekt" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="faeden" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="kreis" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="reichweite" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="webschwierigkeit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="wirkschwierigkeit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="wirkungsdauer" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZAUBER_type")
public class ZAUBERType {

    @XmlAttribute(required = true)
    protected String bezeichnung;
    @XmlAttribute(required = true)
    protected String effekt;
    @XmlAttribute(required = true)
    protected BigInteger faeden;
    @XmlAttribute(required = true)
    protected BigInteger kreis;
    @XmlAttribute(required = true)
    protected String reichweite;
    @XmlAttribute(required = true)
    protected String webschwierigkeit;
    @XmlAttribute(required = true)
    protected String wirkschwierigkeit;
    @XmlAttribute(required = true)
    protected String wirkungsdauer;

    /**
     * Gets the value of the bezeichnung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBezeichnung() {
        return bezeichnung;
    }

    /**
     * Sets the value of the bezeichnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBezeichnung(String value) {
        this.bezeichnung = value;
    }

    /**
     * Gets the value of the effekt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffekt() {
        return effekt;
    }

    /**
     * Sets the value of the effekt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffekt(String value) {
        this.effekt = value;
    }

    /**
     * Gets the value of the faeden property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFaeden() {
        return faeden;
    }

    /**
     * Sets the value of the faeden property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFaeden(BigInteger value) {
        this.faeden = value;
    }

    /**
     * Gets the value of the kreis property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getKreis() {
        return kreis;
    }

    /**
     * Sets the value of the kreis property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setKreis(BigInteger value) {
        this.kreis = value;
    }

    /**
     * Gets the value of the reichweite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReichweite() {
        return reichweite;
    }

    /**
     * Sets the value of the reichweite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReichweite(String value) {
        this.reichweite = value;
    }

    /**
     * Gets the value of the webschwierigkeit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebschwierigkeit() {
        return webschwierigkeit;
    }

    /**
     * Sets the value of the webschwierigkeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebschwierigkeit(String value) {
        this.webschwierigkeit = value;
    }

    /**
     * Gets the value of the wirkschwierigkeit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWirkschwierigkeit() {
        return wirkschwierigkeit;
    }

    /**
     * Sets the value of the wirkschwierigkeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWirkschwierigkeit(String value) {
        this.wirkschwierigkeit = value;
    }

    /**
     * Gets the value of the wirkungsdauer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWirkungsdauer() {
        return wirkungsdauer;
    }

    /**
     * Sets the value of the wirkungsdauer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWirkungsdauer(String value) {
        this.wirkungsdauer = value;
    }

}
